# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mediheaven_pb2 as mediheaven__pb2


class CodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getCode = channel.unary_unary(
                '/mediheaven.Code/getCode',
                request_serializer=mediheaven__pb2.CodeRequest.SerializeToString,
                response_deserializer=mediheaven__pb2.CodeResponse.FromString,
                )
        self.delCode = channel.unary_unary(
                '/mediheaven.Code/delCode',
                request_serializer=mediheaven__pb2.CodeDelRequest.SerializeToString,
                response_deserializer=mediheaven__pb2.SuccessResponse.FromString,
                )
        self.listCode = channel.unary_unary(
                '/mediheaven.Code/listCode',
                request_serializer=mediheaven__pb2.CodeListRequest.SerializeToString,
                response_deserializer=mediheaven__pb2.CodeListResponse.FromString,
                )


class CodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getCode': grpc.unary_unary_rpc_method_handler(
                    servicer.getCode,
                    request_deserializer=mediheaven__pb2.CodeRequest.FromString,
                    response_serializer=mediheaven__pb2.CodeResponse.SerializeToString,
            ),
            'delCode': grpc.unary_unary_rpc_method_handler(
                    servicer.delCode,
                    request_deserializer=mediheaven__pb2.CodeDelRequest.FromString,
                    response_serializer=mediheaven__pb2.SuccessResponse.SerializeToString,
            ),
            'listCode': grpc.unary_unary_rpc_method_handler(
                    servicer.listCode,
                    request_deserializer=mediheaven__pb2.CodeListRequest.FromString,
                    response_serializer=mediheaven__pb2.CodeListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mediheaven.Code', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Code(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediheaven.Code/getCode',
            mediheaven__pb2.CodeRequest.SerializeToString,
            mediheaven__pb2.CodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediheaven.Code/delCode',
            mediheaven__pb2.CodeDelRequest.SerializeToString,
            mediheaven__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediheaven.Code/listCode',
            mediheaven__pb2.CodeListRequest.SerializeToString,
            mediheaven__pb2.CodeListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AccountStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register = channel.unary_unary(
                '/mediheaven.Account/register',
                request_serializer=mediheaven__pb2.RegisterRequest.SerializeToString,
                response_deserializer=mediheaven__pb2.SuccessResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/mediheaven.Account/Login',
                request_serializer=mediheaven__pb2.LoginRequest.SerializeToString,
                response_deserializer=mediheaven__pb2.LoginResponse.FromString,
                )


class AccountServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=mediheaven__pb2.RegisterRequest.FromString,
                    response_serializer=mediheaven__pb2.SuccessResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=mediheaven__pb2.LoginRequest.FromString,
                    response_serializer=mediheaven__pb2.LoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mediheaven.Account', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Account(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediheaven.Account/register',
            mediheaven__pb2.RegisterRequest.SerializeToString,
            mediheaven__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediheaven.Account/Login',
            mediheaven__pb2.LoginRequest.SerializeToString,
            mediheaven__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
