SET
    FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Department;
DROP TABLE IF EXISTS Medicine;
DROP TABLE IF EXISTS Insurance;
DROP TABLE IF EXISTS Administrator;
DROP TABLE IF EXISTS Patient;
DROP TABLE IF EXISTS Medicine_Treat;
DROP TABLE IF EXISTS Physician;
DROP TABLE IF EXISTS Medical_Record;
DROP TABLE IF EXISTS register_code;
DROP TABLE IF EXISTS mykeys;
DROP TABLE IF EXISTS schedule;

SET
    FOREIGN_KEY_CHECKS = 1;