insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (1, 'MethylPREDNISolone', '69');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (2, 'NOXAFIL', '322');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (3, 'Comfort', '265');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (4, 'SILKEN HAND SANITIZER', '635');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (5, 'INSTANT HAND SANITIZER', '705');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (6, 'POTASSIUM CHLORIDE', '21');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (7, 'TopCare', '744');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (8, 'Loratadine', '893');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (9, 'TODAYS HEALTH NASAL RELIEF ORIGINAL', '769');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (10, 'Warfarin Sodium', '919');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (11, 'Total White Brightening', '176');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (12, 'Fluphenazine Hydrochloride', '133');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (13, 'Carbidopa and Levodopa', '378');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (14, 'Morphine SulfateER', '802');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (15, 'Univasc', '401');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (16, 'Molds - Mold Mix 10', '157');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (17, 'nighttime cold and flu relief', '887');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (18, 'Vicks DayQuil', '916');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (19, 'PIRMELLA 1/35', '154');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (20, 'Skin Eruptions', '251');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (21, 'ACID REDUCER', '286');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (22, 'EXTENDED PHENYTOIN SODIUM', '845');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (23, 'La Roche Posay Laboratorie Dermatologique Effaclar Medicated Cleanser', '813');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (24, 'PIRMELLA 1/35', '171');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (25, 'Quetiapine fumarate', '678');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (26, 'Hydromorphone Hydrochloride', '350');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (27, 'PIRMELLA 1/35', '664');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (28, 'smart sense allergy', '318');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (29, 'Ceftriaxone Sodium', '70');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (30, 'Triamterene and Hydrochlorothiazide', '754');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (31, 'Triamterene and Hydrochlorothiazide', '137');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (32, 'PILOCARPINE HYDROCHLORIDE', '934');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (33, 'X Out Spot Corrector', '487');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (34, 'Marjoram Melissa Adult Size', '126');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (35, 'JIANZE ALCOHOL', '20');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (36, 'Tanda pearl professional whitening', '713');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (37, 'Headache', '264');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (38, 'ELF Tinted Moisturizer SPF 15', '63');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (39, 'Famciclovir', '517');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (40, 'Total White Brightening', '476');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (41, 'GMC Medical', '266');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (42, 'DiorSkin Nude 020 Light Beige', '92');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (43, 'Amitriptyline Hydrochloride', '87');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (44, 'ALKERAN', '626');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (45, 'Nadolol', '397');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (46, 'Menopause HP', '878');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (47, 'Heparin Sodium', '373');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (48, 'Hydralazine Hydrochloride', '563');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (49, 'April Bath and Shower Cucumber Melon Scented Hand Sanitizer Anti-Bacterial', '48');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (50, 'Sinus', '996');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (51, 'Daytime Cold and Flu Relief', '502');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (52, 'Nortriptyline Hydrochloride', '308');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (53, 'Comfort', '489');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (54, 'Triamterene and Hydrochlorothiazide', '561');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (55, 'Sleep-Aid', '262');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (56, 'Umcka Original ColdCare', '714');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (57, 'Ibuprofen', '156');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (58, 'CUBA ORIGINAL LADIES ROLL ON ANTIPERSPIRANT DEODORANT', '433');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (59, 'Bumetanide', '393');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (60, 'TopCare', '880');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (61, 'Technetium Tc 99m Medronate', '236');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (62, 'Kiss Fungi-Gone', '498');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (63, 'Risperidone', '18');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (64, 'Oxygen', '833');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (65, 'Pure Finish Mineral Powder Foundation SPF 20 Pure Finish 2', '925');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (66, 'GMC Medical', '114');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (67, 'Divalproex Sodium', '684');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (68, 'Fentanyl Citrate', '704');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (69, 'LBEL COULEUR LUXE AMPLIFIER XP', '184');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (70, 'Bodycology', '653');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (71, 'TopCare', '418');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (72, 'Ranitidine Hydrochloride', '610');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (73, 'Onfi', '975');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (74, 'Ibuprofen', '148');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (75, 'Onfi', '962');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (76, 'Loratadine', '924');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (77, 'temazepam', '430');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (78, 'Flumazenil', '269');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (79, 'SUPER SERUM', '357');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (80, 'Olanzapine', '252');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (81, 'Healthy Accents Ranitidine', '868');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (82, 'LAMIVUDINE', '548');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (83, 'ALKERAN', '221');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (84, 'Hydromorphone Hydrochloride', '163');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (85, 'Granisetron Hydrochloride', '658');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (86, 'MS Contin', '951');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (87, 'Chlorzoxazone', '15');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (88, 'Metronidazole', '39');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (89, 'Technetium Tc 99m Medronate', '327');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (90, 'Oxygen', '321');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (91, 'Bodycology', '565');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (92, 'Goodsense Extra Strength Cold and Hot Medicated', '225');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (93, 'LAMIVUDINE', '425');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (94, 'Carisoprodol', '608');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (95, 'Equate Cough DM', '666');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (96, 'Salt Grass', '410');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (97, 'Warfarin Sodium', '22');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (98, 'Mary Kay TimeWise Repair VoluFirm Day Cream SPF 30', '367');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (99, 'MethylPREDNISolone', '95');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (100, 'Fluphenazine Hydrochloride', '482');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (101, 'Hydralazine Hydrochloride', '821');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (102, 'Nortriptyline Hydrochloride', '849');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (103, 'LYRICA', '953');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (104, 'Mary Kay TimeWise Repair VoluFirm Day Cream SPF 30', '915');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (105, 'NOXAFIL', '576');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (106, 'mally Face Defender Foundation', '305');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (107, 'April Bath and Shower Cucumber Melon Scented Hand Sanitizer Anti-Bacterial', '852');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (108, 'Skin Eruptions', '234');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (109, 'oxycodone hydrochloride', '564');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (110, 'NOXAFIL', '345');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (111, 'healthy accents naproxen sodium', '366');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (112, 'Hydrocodone Bitartrate and Acetaminophen', '789');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (113, 'ADVIL', '947');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (114, 'Famciclovir', '93');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (115, 'Seafood Antigens', '284');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (116, 'AZITHROMYCIN', '983');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (117, 'CALCID', '791');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (118, 'JUGLANS NIGRA POLLEN', '687');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (119, 'topcare flu and severe cold and cough', '394');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (120, 'Elta Tar', '930');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (121, 'NOXAFIL', '778');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (122, 'Mavik', '817');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (123, 'care one sore throat', '267');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (124, 'Stibium 6', '256');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (125, 'Oxygen', '620');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (126, 'Nortriptyline Hydrochloride', '294');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (127, 'Aspirin', '965');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (128, 'Ritalin', '320');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (129, 'Morphine SulfateER', '920');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (130, 'Molds - Mold Mix 10', '399');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (131, 'Oxcarbazepine', '67');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (132, 'Hydralazine Hydrochloride', '446');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (133, 'Salt Grass', '909');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (134, 'Lymph Rx', '382');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (135, 'Activella', '896');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (136, 'Nortriptyline Hydrochloride', '631');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (137, 'Fever Complex', '967');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (138, 'Hawaiian Tropic Kids SPF 30', '556');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (139, 'Hydromorphone Hydrochloride', '556');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (140, 'Hydralazine Hydrochloride', '23');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (141, 'Carbidopa and Levodopa', '250');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (142, 'daytime nighttime', '855');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (143, 'Diphenhydramine Hydrochloride', '78');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (144, 'Divalproex Sodium', '39');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (145, 'LBEL HYDRA CALME SPF 15 Intensive Moisturizing Facial', '495');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (146, 'Risperidone', '223');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (147, 'Ritalin', '49');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (148, 'Warfarin Sodium', '226');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (149, 'Rosmarinus Poterium', '831');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (150, 'GENOTROPIN', '199');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (151, 'Aspirin', '306');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (152, 'Sodum Chloride', '832');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (153, 'Furosemide', '446');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (154, 'Triple Complex UT Tonic', '603');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (155, 'Solar Protection Formula SPF 60 Tinted Concealer - (Blush)', '299');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (156, 'Rosmarinus Poterium', '332');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (157, 'Glyburide', '769');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (158, 'American Beech', '958');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (159, 'METOZOLV', '503');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (160, 'SHISEIDO PERFECT REFINING FOUNDATION', '671');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (161, 'JUGLANS NIGRA POLLEN', '109');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (162, 'Hydromorphone Hydrochloride', '451');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (163, 'Bodycology', '722');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (164, 'Equate Cough DM', '405');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (165, 'Metronidazole', '327');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (166, 'Propranolol Hydrochloride', '508');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (167, 'HEB', '312');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (168, 'Candesartan Cilexetil and Hydrochlorothiazide', '98');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (169, 'Nifedipine', '942');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (170, 'Nauzene', '105');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (171, 'Enalapril Maleate', '278');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (172, 'April Bath and Shower Cucumber Melon Scented Hand Sanitizer Anti-Bacterial', '118');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (173, 'Personal Cloth Wipes', '943');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (174, 'Lisinopril', '975');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (175, 'HAWAIIAN Tropic', '898');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (176, 'Enalapril Maleate', '354');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (177, 'Olay Fresh Effects', '166');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (178, 'Enalapril Maleate', '873');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (179, 'Granisetron Hydrochloride', '155');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (180, 'Sumatriptan', '930');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (181, 'Olanzapine', '46');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (182, 'Nortriptyline Hydrochloride', '380');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (183, 'Oxygen', '515');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (184, 'Equate Cough DM', '53');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (185, 'Hypercalm - Mental Focus', '687');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (186, 'Quetiapine fumarate', '955');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (187, 'Sumatriptan', '461');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (188, 'Cover Fx BB Gel Mattifying Anti-Blemish N Light', '86');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (189, 'Healthy Accents Ranitidine', '212');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (190, 'Propranolol Hydrochloride', '432');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (191, 'Triamterene and Hydrochlorothiazide', '371');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (192, 'LBEL COULEUR LUXE AMPLIFIER XP', '416');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (193, 'SyAllgen', '870');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (194, 'Lisinopril', '377');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (195, 'Aspirin', '307');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (196, 'La Roche Posay Laboratorie Dermatologique Effaclar Medicated Cleanser', '538');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (197, 'Hydrocodone Bitartrate and Acetaminophen', '486');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (198, 'Earwax Removal Aid', '543');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (199, 'CAPTOPRIL', '76');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (200, 'Cover Fx BB Gel Mattifying Anti-Blemish N Light', '469');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (201, 'Paricalcitol', '103');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (202, 'Bacteria Plus', '66');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (203, 'care one sore throat', '24');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (204, 'Equate Cough DM', '237');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (205, 'METOZOLV', '445');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (206, 'Flumazenil', '765');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (207, 'Nortriptyline Hydrochloride', '742');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (208, 'healthy accents naproxen sodium', '711');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (209, 'Daytime Cold and Flu Relief', '490');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (210, 'LBEL HYDRA CALME SPF 15 Intensive Moisturizing Facial', '83');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (211, 'Western Family Hemorrhoidal', '141');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (212, 'LAMIVUDINE', '471');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (213, 'Total White Brightening', '90');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (214, 'Amitriptyline Hydrochloride', '534');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (215, 'Smart Sense Cold Remedy', '426');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (216, '4 in 1 Pressed Mineral SPF 15 Tan', '234');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (217, 'mally Face Defender Foundation', '245');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (218, 'Appetite Enhancer', '803');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (219, 'Menopause HP', '477');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (220, 'Oxygen', '635');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (221, 'ELF Tinted Moisturizer SPF 15', '756');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (222, 'Hydromorphone Hydrochloride', '879');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (223, 'Carisoprodol', '73');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (224, 'Nauzene', '974');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (225, 'AZITHROMYCIN', '700');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (226, 'Oxygen', '438');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (227, 'Hydralazine Hydrochloride', '127');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (228, 'CAFFEINE CITRATE', '896');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (229, 'Hydralazine Hydrochloride', '613');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (230, 'PETROLATUM, LANOLIN', '50');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (231, 'Mavik', '112');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (232, 'PILOCARPINE HYDROCHLORIDE', '531');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (233, 'Nifedipine', '868');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (234, 'nighttime cold and flu relief', '107');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (235, 'Hydrocodone Bitartrate and Acetaminophen', '97');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (236, 'Nifedipine', '151');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (237, 'Umcka Original ColdCare', '85');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (238, 'CALCID', '335');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (239, 'Cooling Acute Pain Relief', '288');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (240, 'Oxcarbazepine', '319');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (241, 'Granisetron Hydrochloride', '378');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (242, 'Erythromycin Base', '507');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (243, 'Daytime Cold and Flu Relief', '913');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (244, 'Rosmarinus Poterium', '294');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (245, 'Olanzapine', '945');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (246, 'ELF Tinted Moisturizer SPF 15', '587');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (247, 'Nauzene', '460');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (248, 'Univasc', '402');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (249, 'Olay Fresh Effects', '596');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (250, 'EXTENDED PHENYTOIN SODIUM', '695');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (251, 'Umcka Original ColdCare', '175');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (252, 'Solar Protection Formula SPF 60 Tinted Concealer - (Blush)', '878');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (253, 'Orabase Benzocaine', '648');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (254, 'PIRMELLA 1/35', '816');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (255, 'Aspirin', '910');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (256, 'GAVISCON', '261');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (257, 'Seafood Antigens', '773');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (258, 'Torsemide', '705');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (259, 'Glipizide', '189');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (260, 'CVS PHARMACY', '225');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (261, 'Fever and Flu', '395');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (262, 'Nortriptyline Hydrochloride', '100');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (263, 'Itchy Scalp', '948');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (264, 'Methylphenidate Hydrochloride', '123');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (265, 'Appetite Enhancer', '154');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (266, 'Furosemide', '43');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (267, 'Fexofenodine Hydrochloride', '807');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (268, 'Amlodipine Besylate', '473');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (269, 'X Out Spot Corrector', '370');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (270, 'Bumetanide', '210');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (271, 'Acetaminophen and Codeine Phosphate', '518');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (272, 'nighttime cold and flu relief', '960');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (273, 'CUBA ORIGINAL LADIES ROLL ON ANTIPERSPIRANT DEODORANT', '824');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (274, 'MS Contin', '120');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (275, 'Hydromorphone Hydrochloride', '160');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (276, 'Carbidopa and Levodopa', '362');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (277, 'GENOTROPIN', '379');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (278, 'Avalide', '298');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (279, 'Nadolol', '472');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (280, 'Flumazenil', '863');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (281, 'Salt Grass', '490');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (282, 'Ergocalciferol', '609');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (283, 'Cover Fx BB Gel Mattifying Anti-Blemish N Light', '736');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (284, 'Famciclovir', '124');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (285, 'SILKEN HAND SANITIZER', '625');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (286, 'Fever Complex', '637');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (287, 'Hydralazine Hydrochloride', '664');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (288, 'La Roche Posay Laboratorie Dermatologique Effaclar Medicated Cleanser', '225');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (289, 'Sumatriptan', '857');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (290, 'Solar Protection Formula SPF 60 Tinted Concealer - (Blush)', '226');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (291, 'Nortriptyline Hydrochloride', '953');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (292, 'Onfi', '708');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (293, 'TODAYS HEALTH NASAL RELIEF ORIGINAL', '671');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (294, 'Nifedipine', '82');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (295, 'Total White Brightening', '201');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (296, 'Onfi', '491');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (297, 'Duloxetine hydrochloride', '376');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (298, 'Tusicof', '867');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (299, 'Bacteria Plus', '434');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (300, 'Hydrocodone Bitartrate and Acetaminophen', '451');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (301, 'Nadolol', '987');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (302, 'Appetite Enhancer', '595');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (303, 'Antibacterial Foaming Hand', '423');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (304, 'temazepam', '394');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (305, 'Loratadine', '830');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (306, 'Warfarin Sodium', '275');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (307, 'Lisinopril', '359');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (308, 'Nortriptyline Hydrochloride', '36');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (309, 'Oxygen', '109');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (310, 'Anastrozole', '740');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (311, 'Oxcarbazepine', '197');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (312, 'Olay Fresh Effects', '983');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (313, 'TODAYS HEALTH NASAL RELIEF ORIGINAL', '516');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (314, 'Enalapril Maleate', '515');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (315, 'GAVISCON', '300');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (316, 'Ceftriaxone Sodium', '437');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (317, 'Cyclosporine', '836');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (318, 'Loratadine', '771');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (319, 'Sinus', '999');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (320, 'X Out Spot Corrector', '513');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (321, 'LBEL COULEUR LUXE AMPLIFIER XP', '774');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (322, 'Cover Fx BB Gel Mattifying Anti-Blemish N Light', '626');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (323, 'Ranitidine Hydrochloride', '805');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (324, 'nighttime cold and flu relief', '478');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (325, 'Sore Throat Logenzes', '231');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (326, 'Western Family Hemorrhoidal', '403');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (327, 'HEB', '156');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (328, 'LBEL HYDRA CALME SPF 15 Intensive Moisturizing Facial', '564');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (329, 'Molds - Mold Mix 10', '240');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (330, 'POTASSIUM CHLORIDE', '545');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (331, 'Acetaminophen and Codeine Phosphate', '951');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (332, 'Western Family Hemorrhoidal', '660');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (333, 'X Out Spot Corrector', '140');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (334, 'NeoStrata Daytime Protection', '256');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (335, 'PILOCARPINE HYDROCHLORIDE', '23');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (336, 'ADVIL', '165');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (337, 'Sugar Maple', '669');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (338, 'ELF Tinted Moisturizer SPF 15', '292');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (339, 'Pacerone', '342');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (340, 'Bodycology', '194');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (341, 'DANDRUFF 2 IN 1 SHAMPOO AND CONDITIONER', '943');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (342, 'Fluphenazine Hydrochloride', '827');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (343, 'Hydralazine Hydrochloride', '604');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (344, 'Fluphenazine Hydrochloride', '712');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (345, 'Sodum Chloride', '54');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (346, 'Olanzapine', '597');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (347, 'Bodycology', '932');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (348, 'healthy accents naproxen sodium', '297');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (349, 'Healthy Accents Ranitidine', '758');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (350, 'Divalproex Sodium', '410');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (351, 'smart sense allergy', '333');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (352, 'Loratadine', '493');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (353, 'Hydromorphone Hydrochloride', '875');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (354, 'Heparin Sodium', '531');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (355, 'Family Care Premium Saline Nasal', '879');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (356, 'PROCHLORPERAZINE', '112');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (357, 'JIANZE ALCOHOL', '666');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (358, 'daytime nighttime', '521');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (359, 'POTASSIUM CHLORIDE', '851');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (360, 'TRAMADOL HYDROCHLORIDE', '623');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (361, 'Enalapril Maleate', '21');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (362, 'Amitriptyline Hydrochloride', '219');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (363, 'Cooling Acute Pain Relief', '608');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (364, 'Univasc', '15');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (365, 'Hydralazine Hydrochloride', '425');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (366, 'Risperidone', '188');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (367, 'Marjoram Melissa Adult Size', '390');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (368, 'Derma-Glove', '208');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (369, 'Triamterene and Hydrochlorothiazide', '22');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (370, 'Epivir', '186');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (371, 'Carbidopa and Levodopa', '710');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (372, 'Warfarin Sodium', '106');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (373, 'Ceftriaxone Sodium', '842');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (374, 'Terazosin', '981');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (375, 'Univasc', '674');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (376, 'Healthy Accents Ranitidine', '406');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (377, 'Skin Eruptions', '722');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (378, 'Hypercalm - Mental Focus', '138');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (379, 'BuPROPion Hydrochloride', '257');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (380, 'Elta Tar', '993');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (381, 'Tanda pearl professional whitening', '639');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (382, 'Metronidazole', '133');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (383, 'April Bath and Shower Cucumber Melon Scented Hand Sanitizer Anti-Bacterial', '512');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (384, 'Flumazenil', '540');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (385, 'Ceftriaxone Sodium', '995');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (386, 'CVS PHARMACY', '170');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (387, 'De La Cruz Castor Oil', '380');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (388, 'Orabase Benzocaine', '651');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (389, 'Sodum Chloride', '282');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (390, 'Methylphenidate Hydrochloride', '94');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (391, 'Regular Strength Aspirin EC', '195');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (392, 'X Out Spot Corrector', '483');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (393, 'TODAYS HEALTH NASAL RELIEF ORIGINAL', '148');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (394, 'Oxygen', '829');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (395, 'Antibacterial Foaming Hand', '548');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (396, 'CVS PHARMACY', '980');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (397, 'Enalapril Maleate', '144');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (398, 'EXSEL SPORT SPF 15', '389');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (399, 'INSTANT HAND SANITIZER', '132');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (400, 'Fever Complex', '212');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (401, 'Nifedipine', '383');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (402, 'Ergocalciferol', '369');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (403, 'Olay Fresh Effects', '702');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (404, 'Umcka Original ColdCare', '9');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (405, 'Anti-bacterial Hand', '679');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (406, 'Sweet Gum', '514');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (407, 'Taraxacum e rad. autumnale 3', '337');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (408, 'Risperidone', '274');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (409, 'Seafood Antigens', '757');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (410, 'Equate Cough DM', '786');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (411, 'Daytime Cold and Flu Relief', '782');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (412, 'CVS PHARMACY', '52');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (413, 'NOXAFIL', '320');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (414, 'ALKERAN', '888');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (415, 'Olay Fresh Effects', '344');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (416, 'LBEL HYDRA CALME SPF 15 Intensive Moisturizing Facial', '688');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (417, 'Sugar Maple', '8');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (418, 'Enalapril Maleate', '239');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (419, 'Taraxacum e rad. autumnale 3', '352');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (420, 'PIRMELLA 1/35', '636');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (421, 'Heparin Sodium', '61');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (422, 'Nauzene', '544');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (423, 'Sumatriptan', '33');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (424, 'ADVIL', '903');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (425, 'Warfarin Sodium', '863');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (426, '4 in 1 Pressed Mineral SPF 15 Tan', '460');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (427, 'Glyburide', '610');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (428, 'CVS PHARMACY', '472');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (429, 'Ibuprofen', '20');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (430, 'Warfarin Sodium', '23');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (431, 'Hydromorphone Hydrochloride', '837');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (432, 'Marjoram Melissa Adult Size', '695');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (433, 'Tusicof', '704');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (434, 'Avalide', '641');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (435, 'Quetiapine Fumarate', '967');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (436, 'JUGLANS NIGRA POLLEN', '104');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (437, 'GAVISCON', '653');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (438, 'ELF Conceler Pencil and Brush', '340');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (439, 'ALKERAN', '696');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (440, 'ALKERAN', '992');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (441, 'Enalapril Maleate', '333');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (442, 'SILKEN HAND SANITIZER', '302');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (443, 'Enalapril Maleate', '733');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (444, 'De La Cruz Castor Oil', '381');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (445, 'Onfi', '348');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (446, 'healthy accents naproxen sodium', '425');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (447, 'PROCHLORPERAZINE', '423');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (448, 'Kiss Fungi-Gone', '839');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (449, 'Epivir', '918');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (450, 'Famciclovir', '245');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (451, 'Fever and Flu', '143');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (452, 'ACID REDUCER', '970');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (453, 'temazepam', '743');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (454, 'April Bath and Shower Cucumber Melon Scented Hand Sanitizer Anti-Bacterial', '29');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (455, 'Ceftriaxone Sodium', '285');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (456, 'Lymph Rx', '767');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (457, 'April Bath and Shower Cucumber Melon Scented Hand Sanitizer Anti-Bacterial', '846');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (458, 'GMC Medical', '584');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (459, 'Amlodipine Besylate', '217');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (460, 'Methylphenidate Hydrochloride', '115');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (461, 'temazepam', '669');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (462, 'April Bath and Shower Cucumber Melon Scented Hand Sanitizer Anti-Bacterial', '129');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (463, 'Paricalcitol', '501');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (464, 'Warfarin Sodium', '577');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (465, 'GAVISCON', '292');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (466, 'LAMIVUDINE', '489');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (467, 'Hydromorphone Hydrochloride', '261');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (468, 'POTASSIUM CHLORIDE', '109');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (469, 'Ranitidine Hydrochloride', '897');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (470, 'Granisetron Hydrochloride', '444');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (471, 'ACID REDUCER', '137');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (472, 'nighttime cold and flu relief', '713');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (473, 'Lisinopril', '477');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (474, 'April Bath and Shower Cucumber Melon Scented Hand Sanitizer Anti-Bacterial', '394');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (475, 'Chrono Repair Solaire', '22');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (476, 'Flumazenil', '950');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (477, 'Aspirin', '599');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (478, 'Amlodipine Besylate', '79');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (479, 'Anti-bacterial Hand', '94');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (480, 'Loratadine', '487');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (481, 'Quetiapine Fumarate', '37');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (482, 'GENOTROPIN', '660');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (483, 'PETROLATUM, LANOLIN', '413');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (484, 'Solar Protection Formula SPF 60 Tinted Concealer - (Blush)', '734');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (485, 'care one sore throat', '443');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (486, 'CALCID', '850');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (487, 'Stibium 6', '430');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (488, 'Avalide', '353');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (489, 'Onfi', '507');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (490, 'Dermadrox', '485');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (491, 'Personal Cloth Wipes', '901');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (492, 'Skin Eruptions', '898');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (493, 'Carisoprodol', '429');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (494, 'Bumetanide', '526');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (495, 'Famciclovir', '220');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (496, 'ELF Conceler Pencil and Brush', '737');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (497, 'Hydralazine Hydrochloride', '523');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (498, 'Salt Grass', '122');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (499, 'Oxcarbazepine', '685');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (500, 'X Out Spot Corrector', '62');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (501, 'Triamterene and Hydrochlorothiazide', '510');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (502, 'Clonidine Hydrochloride', '262');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (503, 'LBEL COULEUR LUXE AMPLIFIER XP', '772');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (504, 'daytime nighttime', '869');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (505, 'Solar Protection Formula SPF 60 Tinted Concealer - (Blush)', '614');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (506, 'Vicks DayQuil', '519');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (507, 'Salt Grass', '659');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (508, 'NeoStrata Daytime Protection', '319');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (509, 'Hawaiian Tropic Kids SPF 30', '153');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (510, 'Fexofenodine Hydrochloride', '937');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (511, 'Cover Fx BB Gel Mattifying Anti-Blemish N Light', '295');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (512, 'SyAllgen', '703');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (513, 'Doxazosin Mesylate', '558');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (514, 'Sinus', '393');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (515, 'Hydromorphone Hydrochloride', '441');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (516, 'oxycodone hydrochloride', '867');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (517, 'Molds - Mold Mix 10', '634');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (518, 'Loratadine', '532');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (519, 'Bumetanide', '110');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (520, 'HEB', '731');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (521, 'Avalide', '740');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (522, 'LYRICA', '990');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (523, 'Lymph Rx', '821');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (524, 'American Beech', '744');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (525, 'AZITHROMYCIN', '620');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (526, 'Amitriptyline Hydrochloride', '418');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (527, 'daytime nighttime', '847');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (528, 'Technetium Tc 99m Medronate', '905');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (529, 'Nifedipine', '117');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (530, 'Imiquimod', '792');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (531, 'TODAYS HEALTH NASAL RELIEF ORIGINAL', '745');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (532, 'TopCare', '64');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (533, 'Antibacterial Foaming Hand', '562');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (534, 'LBEL HYDRA CALME SPF 15 Intensive Moisturizing Facial', '130');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (535, 'Vicks DayQuil', '158');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (536, 'Sumatriptan', '907');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (537, 'PILOCARPINE HYDROCHLORIDE', '165');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (538, 'Lymph Rx', '540');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (539, 'nighttime cold and flu relief', '771');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (540, 'Sore Throat Logenzes', '923');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (541, 'temazepam', '784');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (542, 'Personal Cloth Wipes', '225');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (543, 'Glipizide', '998');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (544, 'Quetiapine Fumarate', '446');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (545, 'temazepam', '344');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (546, 'JIANZE ALCOHOL', '462');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (547, 'Pacerone', '707');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (548, 'Bumetanide', '337');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (549, 'ADVIL', '799');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (550, 'temazepam', '712');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (551, 'Hydralazine Hydrochloride', '983');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (552, 'Amlodipine Besylate', '766');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (553, 'April Bath and Shower Cucumber Melon Scented Hand Sanitizer Anti-Bacterial', '845');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (554, 'Vicks DayQuil', '721');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (555, 'PIRMELLA 1/35', '968');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (556, 'Warfarin Sodium', '400');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (557, 'Comfort', '928');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (558, 'Quetiapine Fumarate', '69');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (559, 'LYRICA', '478');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (560, 'Fentanyl Citrate', '763');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (561, 'De La Cruz Castor Oil', '901');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (562, 'La Roche Posay Laboratorie Dermatologique Effaclar Medicated Cleanser', '485');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (563, 'Pollens - Weeds and Garden Plants, Scale, Wing (Shad) Atriplex canescens', '398');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (564, 'Ibuprofen', '718');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (565, 'Sleep-Aid', '876');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (566, 'Quetiapine Fumarate', '514');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (567, 'Salt Grass', '402');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (568, 'Equate Cough DM', '413');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (569, 'GMC Medical', '112');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (570, 'Enalapril Maleate', '368');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (571, 'NeoStrata Daytime Protection', '517');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (572, 'Taraxacum e rad. autumnale 3', '669');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (573, 'ELF Tinted Moisturizer SPF 15', '190');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (574, 'TODAYS HEALTH NASAL RELIEF ORIGINAL', '822');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (575, 'ELF Conceler Pencil and Brush', '690');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (576, 'Taraxacum e rad. autumnale 3', '204');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (577, 'Seafood Antigens', '476');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (578, 'ACID REDUCER', '94');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (579, 'Nortriptyline Hydrochloride', '944');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (580, 'Carisoprodol', '577');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (581, 'Nadolol', '106');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (582, 'Triamterene and Hydrochlorothiazide', '701');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (583, 'Olanzapine', '447');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (584, 'Methylphenidate Hydrochloride', '173');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (585, 'Terazosin', '294');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (586, 'AXIRON', '633');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (587, 'Molds, Rusts and Smuts, Hormodendrum cladosporioides', '351');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (588, 'SUPER SERUM', '316');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (589, 'Oxygen', '585');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (590, 'Skin Eruptions', '148');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (591, 'MS Contin', '813');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (592, 'Cover Fx BB Gel Mattifying Anti-Blemish N Light', '811');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (593, 'Cyclosporine', '417');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (594, 'Cooling Acute Pain Relief', '880');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (595, 'Triamterene and Hydrochlorothiazide', '993');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (596, 'HEB', '833');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (597, 'Family Care Premium Saline Nasal', '49');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (598, 'Ampicillin and Sulbactam', '717');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (599, 'MethylPREDNISolone', '348');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (600, 'Fexofenodine Hydrochloride', '994');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (601, 'Nortriptyline Hydrochloride', '788');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (602, 'Sore Throat Logenzes', '189');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (603, 'Bodycology', '709');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (604, 'ACID REDUCER', '419');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (605, 'Hydralazine Hydrochloride', '350');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (606, 'Furosemide', '992');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (607, 'Family Care Premium Saline Nasal', '549');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (608, 'Hydrocodone Bitartrate and Acetaminophen', '551');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (609, 'Divalproex Sodium', '326');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (610, 'LYRICA', '881');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (611, 'oxycodone hydrochloride', '363');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (612, 'LAMIVUDINE', '842');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (613, 'Candesartan Cilexetil and Hydrochlorothiazide', '306');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (614, 'Imiquimod', '4');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (615, 'Paricalcitol', '837');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (616, 'Salt Grass', '572');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (617, 'Paricalcitol', '789');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (618, 'CALCID', '66');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (619, 'Family Care Premium Saline Nasal', '86');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (620, 'Methylphenidate Hydrochloride', '310');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (621, 'Warfarin Sodium', '156');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (622, 'Sore Throat Logenzes', '449');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (623, 'Ceftriaxone Sodium', '797');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (624, 'Lisinopril', '50');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (625, 'HEB', '213');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (626, 'Healthy Accents Ranitidine', '648');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (627, 'Terazosin', '554');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (628, 'nighttime cold and flu relief', '97');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (629, 'Ibuprofen', '775');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (630, 'Nortriptyline Hydrochloride', '47');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (631, 'Monoket', '519');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (632, 'Itchy Scalp', '957');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (633, 'oxycodone hydrochloride', '206');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (634, 'PETROLATUM, LANOLIN', '614');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (635, 'Pollens - Weeds and Garden Plants, Scale, Wing (Shad) Atriplex canescens', '34');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (636, 'Itchy Scalp', '345');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (637, 'TRAMADOL HYDROCHLORIDE', '301');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (638, 'Quetiapine Fumarate', '564');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (639, 'nighttime cold and flu relief', '248');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (640, 'Doxazosin Mesylate', '188');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (641, 'Clonidine Hydrochloride', '491');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (642, 'Skin Eruptions', '716');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (643, 'Sumatriptan', '847');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (644, 'Omeprazole', '644');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (645, 'Cooling Acute Pain Relief', '838');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (646, 'Comfort', '576');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (647, 'Fever and Flu', '60');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (648, 'Ceftriaxone Sodium', '990');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (649, 'Glipizide', '737');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (650, 'Terazosin', '72');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (651, 'Marjoram Melissa Adult Size', '504');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (652, 'CAFFEINE CITRATE', '426');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (653, 'Propranolol Hydrochloride', '794');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (654, 'Heparin Sodium', '122');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (655, 'DiorSkin Nude 020 Light Beige', '771');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (656, 'Healthy Accents Ranitidine', '59');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (657, 'Erythromycin Base', '808');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (658, 'Fexofenodine Hydrochloride', '360');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (659, 'Famciclovir', '937');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (660, 'Sumatriptan', '498');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (661, 'Hydromorphone Hydrochloride', '439');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (662, 'Fever and Flu', '432');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (663, 'Smart Sense Cold Remedy', '250');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (664, 'Triple Complex UT Tonic', '264');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (665, 'Heparin Sodium', '974');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (666, 'Western Family Hemorrhoidal', '645');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (667, 'Doxazosin Mesylate', '319');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (668, 'Oxygen', '662');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (669, 'Glyburide', '488');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (670, 'Tusicof', '113');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (671, 'Sugar Maple', '975');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (672, 'Orabase Benzocaine', '471');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (673, 'Hydromorphone Hydrochloride', '940');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (674, 'Pure Finish Mineral Powder Foundation SPF 20 Pure Finish 2', '617');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (675, 'Fever and Flu', '277');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (676, 'IQ Derma Essentials Life Without Wrinkles', '194');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (677, 'Salt Grass', '711');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (678, 'Nortriptyline Hydrochloride', '699');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (679, 'EXTENDED PHENYTOIN SODIUM', '308');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (680, 'topcare flu and severe cold and cough', '983');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (681, 'Hawaiian Tropic Kids SPF 30', '489');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (682, 'Sleep-Aid', '98');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (683, 'CAFFEINE CITRATE', '303');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (684, 'April Bath and Shower Cucumber Melon Scented Hand Sanitizer Anti-Bacterial', '680');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (685, 'POTASSIUM CHLORIDE', '708');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (686, 'TODAYS HEALTH NASAL RELIEF ORIGINAL', '26');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (687, 'Daytime Cold and Flu Relief', '133');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (688, 'Earwax Removal Aid', '208');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (689, 'Carbidopa and Levodopa', '586');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (690, 'Ampicillin and Sulbactam', '856');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (691, 'Tanda pearl professional whitening', '283');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (692, 'Healthy Accents Ranitidine', '625');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (693, 'Menopause HP', '475');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (694, 'Imiquimod', '960');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (695, 'Healthy Accents Ranitidine', '496');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (696, 'Clonidine Hydrochloride', '219');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (697, 'Heparin Sodium', '536');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (698, 'TRAMADOL HYDROCHLORIDE', '537');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (699, 'EXTENDED PHENYTOIN SODIUM', '920');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (700, 'Lisinopril', '423');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (701, 'GAVISCON', '237');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (702, 'Goodsense Extra Strength Cold and Hot Medicated', '85');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (703, 'Molds - Mold Mix 10', '730');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (704, 'Menopause HP', '762');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (705, 'Marjoram Melissa Adult Size', '629');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (706, 'Candesartan Cilexetil and Hydrochlorothiazide', '766');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (707, 'GAVISCON', '214');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (708, 'Amlodipine Besylate', '288');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (709, 'oxycodone hydrochloride', '14');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (710, 'Elta Tar', '416');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (711, 'Elta Tar', '846');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (712, 'CUBA ORIGINAL LADIES ROLL ON ANTIPERSPIRANT DEODORANT', '182');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (713, 'Hydrocodone Bitartrate and Acetaminophen', '377');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (714, 'Mary Kay TimeWise Repair VoluFirm Day Cream SPF 30', '457');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (715, 'Hydralazine Hydrochloride', '930');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (716, 'GMC Medical', '124');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (717, 'Healthy Accents Ranitidine', '403');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (718, 'LBEL COULEUR LUXE AMPLIFIER XP', '887');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (719, 'Carisoprodol', '788');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (720, 'AXIRON', '346');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (721, 'Seafood Antigens', '475');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (722, 'TODAYS HEALTH NASAL RELIEF ORIGINAL', '223');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (723, 'Aspirin', '542');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (724, 'Ibuprofen', '311');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (725, 'ELF Conceler Pencil and Brush', '332');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (726, 'nighttime cold and flu relief', '430');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (727, 'SUPER SERUM', '220');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (728, 'Nadolol', '730');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (729, 'Elta Tar', '38');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (730, 'Menopause HP', '271');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (731, 'Avalide', '404');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (732, 'HAWAIIAN Tropic', '400');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (733, 'Chrono Repair Solaire', '370');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (734, 'Hypercalm - Mental Focus', '959');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (735, 'Nadolol', '56');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (736, 'Tanda pearl professional whitening', '704');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (737, 'GAVISCON', '641');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (738, 'Amlodipine Besylate', '867');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (739, 'healthy accents daytime nighttime', '316');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (740, 'CVS PHARMACY', '976');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (741, 'PETROLATUM, LANOLIN', '442');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (742, 'Olanzapine', '993');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (743, 'HAWAIIAN Tropic', '82');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (744, 'NeoStrata Daytime Protection', '126');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (745, 'CALCID', '958');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (746, 'Marjoram Melissa Adult Size', '930');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (747, 'Technetium Tc 99m Medronate', '608');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (748, 'De La Cruz Castor Oil', '741');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (749, 'BuPROPion Hydrochloride', '934');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (750, 'Paricalcitol', '281');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (751, 'smart sense allergy', '798');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (752, 'Sore Throat Logenzes', '287');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (753, 'Cover Fx BB Gel Mattifying Anti-Blemish N Light', '626');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (754, 'Hawaiian Tropic Kids SPF 30', '645');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (755, 'oxycodone hydrochloride', '326');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (756, 'Paricalcitol', '245');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (757, 'Bacteria Plus', '778');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (758, 'AZITHROMYCIN', '86');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (759, 'Epivir', '8');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (760, 'CVS PHARMACY', '713');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (761, 'AXIRON', '774');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (762, 'Ibuprofen', '589');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (763, 'EXTENDED PHENYTOIN SODIUM', '668');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (764, 'Salt Grass', '654');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (765, 'Univasc', '91');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (766, 'April Bath and Shower Cucumber Melon Scented Hand Sanitizer Anti-Bacterial', '692');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (767, 'Technetium Tc 99m Medronate', '597');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (768, 'Salt Grass', '792');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (769, 'EXSEL SPORT SPF 15', '587');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (770, 'Divalproex Sodium', '57');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (771, 'April Bath and Shower Cucumber Melon Scented Hand Sanitizer Anti-Bacterial', '106');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (772, 'HAWAIIAN Tropic', '515');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (773, 'Ampicillin and Sulbactam', '678');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (774, 'Daytime Cold and Flu Relief', '275');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (775, 'Nifedipine', '182');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (776, 'Nadolol', '80');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (777, 'Sweet Gum', '69');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (778, 'Sodum Chloride', '427');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (779, 'Sugar Maple', '189');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (780, 'ELF Conceler Pencil and Brush', '48');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (781, 'Personal Cloth Wipes', '158');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (782, 'CUBA ORIGINAL LADIES ROLL ON ANTIPERSPIRANT DEODORANT', '1000');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (783, 'Itchy Scalp', '23');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (784, 'LAMIVUDINE', '760');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (785, 'Heparin Sodium', '408');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (786, 'NeoStrata Daytime Protection', '333');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (787, 'Kiss Fungi-Gone', '909');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (788, 'ACID REDUCER', '809');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (789, 'temazepam', '208');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (790, 'LBEL HYDRA CALME SPF 15 Intensive Moisturizing Facial', '46');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (791, 'Fever Complex', '481');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (792, 'Bacteria Plus', '687');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (793, 'American Beech', '10');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (794, 'PILOCARPINE HYDROCHLORIDE', '724');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (795, 'GAVISCON', '772');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (796, 'ALKERAN', '455');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (797, 'PILOCARPINE HYDROCHLORIDE', '299');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (798, 'Bumetanide', '747');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (799, 'Allergena', '411');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (800, 'Hydromorphone Hydrochloride', '685');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (801, 'Aspirin', '425');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (802, 'IQ Derma Essentials Life Without Wrinkles', '121');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (803, 'Hydralazine Hydrochloride', '734');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (804, 'Fever Complex', '605');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (805, 'IQ Derma Essentials Life Without Wrinkles', '483');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (806, 'LBEL HYDRA CALME SPF 15 Intensive Moisturizing Facial', '957');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (807, 'Heparin Sodium', '888');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (808, 'ADVIL', '449');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (809, 'LBEL HYDRA CALME SPF 15 Intensive Moisturizing Facial', '571');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (810, 'ELF Tinted Moisturizer SPF 15', '883');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (811, 'Technetium Tc 99m Medronate', '461');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (812, 'Clonidine Hydrochloride', '334');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (813, 'Dermadrox', '820');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (814, 'Sore Throat Logenzes', '853');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (815, 'Quetiapine Fumarate', '295');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (816, 'Amitriptyline Hydrochloride', '787');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (817, 'Univasc', '209');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (818, '4 in 1 Pressed Mineral SPF 15 Tan', '828');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (819, 'Molds - Mold Mix 10', '769');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (820, 'Torsemide', '264');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (821, 'Regular Strength Aspirin EC', '688');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (822, 'DiorSkin Nude 020 Light Beige', '576');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (823, 'Acetaminophen and Codeine Phosphate', '732');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (824, 'Vicks DayQuil', '135');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (825, 'Chlorzoxazone', '211');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (826, 'JUGLANS NIGRA POLLEN', '438');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (827, 'Taraxacum e rad. autumnale 3', '758');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (828, 'AZITHROMYCIN', '327');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (829, 'PETROLATUM, LANOLIN', '978');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (830, 'Risperidone', '519');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (831, 'NOXAFIL', '429');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (832, 'IQ Derma Essentials Life Without Wrinkles', '31');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (833, 'Personal Cloth Wipes', '200');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (834, 'Amlodipine Besylate', '237');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (835, 'HAWAIIAN Tropic', '811');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (836, 'TopCare', '696');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (837, 'daytime nighttime', '892');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (838, 'CVS PHARMACY', '653');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (839, 'MethylPREDNISolone', '458');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (840, 'Fentanyl Citrate', '910');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (841, 'Bacteria Plus', '306');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (842, 'Sugar Maple', '815');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (843, 'Amitriptyline Hydrochloride', '823');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (844, 'Sore Throat Logenzes', '711');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (845, 'Solar Protection Formula SPF 60 Tinted Concealer - (Blush)', '358');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (846, 'IQ Derma Essentials Life Without Wrinkles', '153');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (847, 'Fever and Flu', '944');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (848, 'Healthy Accents Ranitidine', '613');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (849, 'Equate Cough DM', '591');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (850, 'Regular Strength Aspirin EC', '450');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (851, 'Divalproex Sodium', '67');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (852, 'Furosemide', '905');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (853, 'Sleep-Aid', '618');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (854, 'PROCHLORPERAZINE', '885');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (855, 'American Beech', '230');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (856, 'CVS PHARMACY', '484');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (857, 'SUPER SERUM', '390');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (858, 'Pacerone', '831');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (859, 'Monoket', '41');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (860, 'Tanda pearl professional whitening', '510');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (861, 'Diphenhydramine Hydrochloride', '524');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (862, 'Total White Brightening', '631');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (863, 'Fever and Flu', '570');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (864, 'EXTENDED PHENYTOIN SODIUM', '190');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (865, 'AZITHROMYCIN', '194');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (866, 'Flumazenil', '107');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (867, 'CVS PHARMACY', '996');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (868, 'Glipizide', '409');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (869, 'Propranolol Hydrochloride', '790');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (870, 'Cooling Acute Pain Relief', '368');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (871, 'ELF Tinted Moisturizer SPF 15', '806');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (872, 'Metronidazole', '83');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (873, 'Cooling Acute Pain Relief', '405');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (874, 'Methylphenidate Hydrochloride', '75');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (875, 'Aspirin', '530');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (876, 'Nauzene', '968');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (877, 'Pure Finish Mineral Powder Foundation SPF 20 Pure Finish 2', '415');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (878, 'Nauzene', '610');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (879, 'Total White Brightening', '670');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (880, 'Imiquimod', '633');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (881, 'Hydralazine Hydrochloride', '774');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (882, 'Cooling Acute Pain Relief', '943');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (883, 'Warfarin Sodium', '807');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (884, 'Morphine SulfateER', '838');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (885, 'Umcka Original ColdCare', '549');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (886, 'Carisoprodol', '481');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (887, 'Granisetron Hydrochloride', '921');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (888, 'Quetiapine fumarate', '850');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (889, 'Fentanyl Citrate', '255');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (890, 'Mavik', '319');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (891, 'Glyburide', '351');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (892, 'NOXAFIL', '565');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (893, 'Headache', '910');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (894, 'Ranitidine Hydrochloride', '636');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (895, 'NeoStrata Daytime Protection', '311');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (896, 'Marjoram Melissa Adult Size', '544');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (897, 'Aspirin', '773');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (898, 'Bumetanide', '965');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (899, 'Umcka Original ColdCare', '834');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (900, 'Family Care Premium Saline Nasal', '367');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (901, 'Solar Protection Formula SPF 60 Tinted Concealer - (Blush)', '461');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (902, 'Avalide', '420');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (903, 'Personal Cloth Wipes', '617');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (904, 'Healthy Accents Ranitidine', '493');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (905, 'Allergena', '250');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (906, 'Cooling Acute Pain Relief', '187');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (907, 'Morphine SulfateER', '749');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (908, 'Regular Strength Aspirin EC', '677');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (909, 'SHISEIDO PERFECT REFINING FOUNDATION', '641');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (910, 'PIRMELLA 1/35', '276');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (911, 'GENOTROPIN', '785');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (912, 'Erythromycin Base', '21');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (913, 'Sodum Chloride', '908');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (914, 'Sumatriptan', '482');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (915, 'EXTENDED PHENYTOIN SODIUM', '993');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (916, 'Hydromorphone Hydrochloride', '485');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (917, 'Carisoprodol', '851');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (918, 'Pollens - Weeds and Garden Plants, Scale, Wing (Shad) Atriplex canescens', '915');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (919, 'Equate Cough DM', '344');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (920, 'Cover Fx BB Gel Mattifying Anti-Blemish N Light', '3');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (921, 'JIANZE ALCOHOL', '172');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (922, 'care one sore throat', '48');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (923, 'Anastrozole', '715');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (924, 'LAMIVUDINE', '947');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (925, 'Healthy Accents Ranitidine', '356');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (926, 'INSTANT HAND SANITIZER', '515');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (927, 'CVS PHARMACY', '236');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (928, 'Quetiapine Fumarate', '992');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (929, 'SUPER SERUM', '106');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (930, 'Earwax Removal Aid', '108');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (931, 'Appetite Enhancer', '666');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (932, 'temazepam', '972');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (933, 'ELF Tinted Moisturizer SPF 15', '643');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (934, 'April Bath and Shower Cucumber Melon Scented Hand Sanitizer Anti-Bacterial', '412');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (935, 'Sumatriptan', '347');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (936, 'Paricalcitol', '700');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (937, 'daytime nighttime', '613');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (938, 'CAFFEINE CITRATE', '940');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (939, 'ACID REDUCER', '439');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (940, 'Hydrocodone Bitartrate and Acetaminophen', '739');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (941, 'MS Contin', '662');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (942, 'Cooling Acute Pain Relief', '935');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (943, 'Activella', '317');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (944, 'Salt Grass', '725');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (945, 'Heparin Sodium', '510');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (946, 'TRAMADOL HYDROCHLORIDE', '73');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (947, 'care one sore throat', '566');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (948, 'Hydrocodone Bitartrate and Acetaminophen', '174');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (949, 'LBEL COULEUR LUXE AMPLIFIER XP', '219');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (950, 'Hypercalm - Mental Focus', '6');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (951, 'Bumetanide', '149');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (952, 'Nortriptyline Hydrochloride', '897');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (953, 'Hydrocodone Bitartrate and Acetaminophen', '100');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (954, 'Rosmarinus Poterium', '586');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (955, 'Regular Strength Aspirin EC', '667');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (956, 'Amitriptyline Hydrochloride', '180');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (957, 'IQ Derma Essentials Life Without Wrinkles', '653');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (958, 'Sleep-Aid', '862');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (959, '4 in 1 Pressed Mineral SPF 15 Tan', '116');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (960, 'Mary Kay TimeWise Repair VoluFirm Day Cream SPF 30', '343');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (961, 'ADVIL', '945');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (962, 'Ranitidine Hydrochloride', '168');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (963, 'Enalapril Maleate', '322');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (964, '4 in 1 Pressed Mineral SPF 15 Tan', '307');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (965, 'GENOTROPIN', '710');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (966, 'CAPTOPRIL', '403');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (967, 'SHISEIDO PERFECT REFINING FOUNDATION', '958');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (968, 'Limencin Patch', '567');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (969, 'Nortriptyline Hydrochloride', '254');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (970, 'Orabase Benzocaine', '568');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (971, 'Lisinopril', '742');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (972, 'Bodycology', '184');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (973, 'Univasc', '252');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (974, 'Onfi', '628');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (975, 'EXSEL SPORT SPF 15', '799');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (976, 'Limencin Patch', '44');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (977, 'Hydromorphone Hydrochloride', '456');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (978, 'HAWAIIAN Tropic', '654');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (979, 'Equate Cough DM', '704');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (980, 'CAPTOPRIL', '688');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (981, 'Torsemide', '118');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (982, 'Sugar Maple', '264');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (983, 'Candesartan Cilexetil and Hydrochlorothiazide', '359');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (984, 'AXIRON', '308');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (985, 'Nadolol', '28');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (986, 'Oxygen', '757');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (987, 'POTASSIUM CHLORIDE', '825');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (988, 'Enalapril Maleate', '38');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (989, 'Pure Finish Mineral Powder Foundation SPF 20 Pure Finish 2', '642');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (990, 'X Out Spot Corrector', '426');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (991, 'Headache', '483');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (992, 'Antibacterial Foaming Hand', '554');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (993, 'DiorSkin Nude 020 Light Beige', '706');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (994, 'Glipizide', '622');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (995, 'MethylPREDNISolone', '626');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (996, 'Total White Brightening', '504');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (997, 'Famciclovir', '680');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (998, 'NeoStrata Daytime Protection', '102');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (999, 'Hydralazine Hydrochloride', '502');
insert into MOCK_DATA (ID, Medicine_Name, Record_ID) values (1000, 'Hydralazine Hydrochloride', '756');
